plugins {
  id 'java-library'
  id 'maven-publish'
  id 'signing'
  id 'com.adarshr.test-logger' version '4.0.0'
}


description = 'Java Pack Library'
group = 'de.sayayi.lib'
version = libs.versions.pack.get()


layout.buildDirectory = '.build'


java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}


javadoc {
  javadocTool = javaToolchains.javadocToolFor {
    languageVersion = JavaLanguageVersion.of(21)
  }
}


test {
  useJUnitPlatform()

  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(21)
  }
}


repositories {
  mavenCentral()
}


dependencies {
  // java
  compileOnlyApi libs.jetbrains.annotations
  compileOnlyApi(libs.tika.core) {
    transitive = false
  }

  // test
  testImplementation libs.junit.jupiter.api
  testImplementation libs.junit.jupiter.params
  testRuntimeOnly libs.junit.jupiter.engine
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

  testImplementation libs.tika.core
}


def resolvedJetbrainsAnnotationsVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'annotations' }
    .moduleVersion.id.version
def resolvedTikaVersion = configurations
    .compileClasspath
    .resolvedConfiguration
    .resolvedArtifacts
    .find { it.name == 'tika-core' }
    .moduleVersion.id.version


javadoc {
  title = "Java Pack Library ${version}"

  (options as StandardJavadocDocletOptions).with {
    linksOffline "https://javadoc.io/doc/org.jetbrains/annotations/${resolvedJetbrainsAnnotationsVersion}/",
                 'gradle/javadocs/jetbrains-annotations'
    linksOffline "https://javadoc.io/doc/org.apache.tika/tika-core/${resolvedTikaVersion}/",
                 'gradle/javadocs/tika-core'

    encoding 'UTF-8'

    noQualifiers 'java.util', 'java.lang'

    addStringOption('Xdoclint:-missing', '-quiet')
  }

  failOnError = false
}


tasks.withType(Jar).configureEach {
  reproducibleFileOrder = true

  manifest {
    attributes(
        'Implementation-Vendor': 'Jeroen Gremmen',
        'Implementation-Vendor-Id': 'de.sayayi',
        'Implementation-Title': project.name,
        'Implementation-Version': project.version,
        'Created-By': "${System.getProperty('java.version')} (${System.getProperty('java.specification.vendor')})",
        'Built-Date': new Date().format('yyyy-MM-dd HH:mm:ss')
    )
  }

  metaInf {
    from files('LICENSE')
  }
}


jar {
  dependsOn test
}


tasks.register('javadocJar', Jar) {
  archiveClassifier.set('javadoc')
  from javadoc
}


tasks.register('sourcesJar', Jar) {
  dependsOn classes

  archiveClassifier.set('sources')
  from sourceSets.main.allSource
}


testlogger {
  theme = 'mocha'
  slowThreshold = 2500
}


def snapshot = version.toString().endsWith('-SNAPSHOT')
def tmpRepositoryDirectory = rootProject.layout.buildDirectory
    .dir('repository').get()
    .dir(snapshot ? 'snapshot' : 'release')
    .asFile


publishing {
  publications {
    create('maven', MavenPublication) {
      from components.java

      artifact javadocJar
      artifact sourcesJar

      pom {
        name = 'Java Pack Library'
        description = "Java Pack Library"
        url = 'https://github.com/jgremmen/zbdd'
        inceptionYear = '2021'

        licenses {
          license {
            name = 'Apache License, Version 2.0'
            url = 'https://www.apache.org/licenses/LICENSE-2.0'
            distribution = 'repo'
          }
        }

        developers {
          developer {
            id = 'jgremmen'
            name = 'Jeroen Gremmen'
            email = 'jeroen.gremmen@sayayi.de'
          }
        }

        scm {
          connection = 'scm:git:git://github.com/jgremmen/pack.git'
          developerConnection = 'scm:git:git://github.com/jgremmen/pack.git'
          url = 'https://github.com/jgremmen/pack'
        }
      }
    }
  }

  repositories {
    maven {
      name = 'mavenTemp'
      url = tmpRepositoryDirectory
    }
    maven {
      name = 'mavenCentral'
      url = snapshot
          ? 'https://oss.sonatype.org/content/repositories/snapshots'
          : 'https://oss.sonatype.org/service/local/staging/deploy/maven2'

      credentials {
        username = project.findProperty('mavenCentral.username')
        password = project.findProperty('mavenCentral.password')
      }
    }
  }
}


signing {
  sign publishing.publications.maven
}
